---
title: "Material"
---

Podem encontrar o material para a cadeira nesta página, organizado por capítulo.

## Slides

### Capítulo I: Racionalidade e Vantagens do Comêrcio

1. [Introdução](slides/01_Intro.qmd)
2. [Escolhas Racionais](slides/02_Escolhas_Racionais.qmd)
3. [FPP e Ventagens do Comêrcio](slides/03_FPP.qmd)

### Capítulo II: Teoria do Consumidor e Procura

4. [Restrição Orçamental e Preferências](slides/04_Cabaz_restricao_preferencias.qmd)
5. [Utilidade e procura](slides/05_Utilidade_gossen_procura.qmd)
6. [Procura agregada a excedente](slides/06_Procura_excedente.qmd)


### Capítulo III: Teoría da Produção - Curto Prazo

7. [Conceitos](slides/07_Producao_cp_lp.qmd)
8. [Etapas Processo Produtivo e Regra da Contratação](slides/08_Etapas_contratacao.qmd)
9. [Função de Custos](slides/09_Funcao_custos.qmd)
10. [Geometria de Custos](slides/10_Geometria_custos.qmd)
11. [Otimização num mercado concorrencial](slides/11_Otimizacao_concorrencial.qmd)

### Capítulo IV: Equilíbrio de Mercado de Curto Prazo

12. [Oferta](slides/12_Oferta.qmd)
13. [Equilíbrio de Curto Prazo](slides/13_Eq_cp.qmd)

### Capítulo V: Produção e Equilíbrio de Mercado de Longo Prazo

14. [Longo Prazo](slides/14_Lp_isoquanta.qmd)
15. [Equilíbrio de Longo Prazo](slides/15_Eq_mercado_oferta_lp.qmd)

### Capítulo VI: Elasticidades e Intervenções dos Mercados

16. [Elasticidade da Procura](slides/16_elasticidades_procura.qmd)
17. [Elasticidade da Oferta](slides/17_elasticidade_oferta.qmd)
18. [Impostos](slides/18_impostos_elasticidade.qmd)
19. [Subsídios](slides/19_subsidios.qmd)
20. [Intervenções](slides/20_intervencoes.qmd)
]

### Capítulo VII: Monopólio e Oligopólio, Introdução à Teoria de Jogos


## Outro Material

* [Bridge Produtor](slides/motivacao_produtor.qmd)